### ISSUE TITLE
Automatically wipe image caches for documentation badges when documentation is updated

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark-docbot#3]
Futhark packages are supposed to link to the newest documentation by including in their README a link `https://futhark-lang.org/pkgs/FOO/docs/latest`, along with the image `https://futhark-lang.org/pkgs/github.com/diku-dk/FOO/status.svg`.  This image also embeds a version number.  For example, `https://futhark-lang.org/pkgs/github.com/diku-dk/segmented/status.svg` looks like this: [![Documentation](https://futhark-lang.org/pkgs/github.com/diku-dk/segmented/status.svg)](https://futhark-lang.org/pkgs/github.com/diku-dk/segmented/latest/).  It can be seen in action [here](https://github.com/diku-dk/segmented).

The problem is that GitHub will download that image once, upload it to their CDN, then use the cached version forever.  Even as the `segmented` package receives a new release, the badge will keep the old version number.  That sucks.  Most people solve this by adding various cache control headers to the website that serve the badge.  This is not viable for us, as the Futhark infrastructure is built entirely around zero-configuration (and zero-*maintenance*) webservers serving static files.

Fortunately, there is a way for *anyone* to clear one of these image caches:

```
$ curl -X PURGE https://camo.githubusercontent.com/9c6d694de8eb254d64ab31605772ba4324644ccd/68747470733a2f2f6675746861726b2d6c616e672e6f72672f706b67732f6769746875622e636f6d2f64696b752d646b2f7365676d656e7465642f7374617475732e737667
```

Where that long URL is whatever the image was cached under.  This URL is not predictable, but can be determined by reading the HTML generated by GitHub for the README file.  On the next load of the README, GitHub will retrieve the new version of the image from the webserver.

We can do this manually, but that would suck.  Instead, the Travis job for `futhark-docbot` should go through the READMEs for all known Futhark packages, fish out the badge image URLs, and `curl -x PURGE` them.  As an optimisation, we technically only have to do this for packages that have received a new release since the last time the script was run, but I don't think this matters much.

**Comment by svip** [comment]
Implemented this issue.  It runs naïvely at this point, i.e. purging any status images it comes across, even if it didn't actually need purging.  I doubt Github will be too bothered by that.

It won't report an error if the README file contains no status image, but it will report an error if there is no README file at all.  However, none of its errors are considered fatal, so the script will continue regardless.

You may wish to modify the stdout, if you don't wish to see the entire status image URL it purges.
