### ISSUE TITLE
New additions haven't been picked up

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark-docbot#5]
It looks like img-fut was added on Feb 10, but https://futhark-lang.org/pkgs/ doesn't seem to have been updated. Has the travis script broken?

**Comment by athas** [comment]
`img-fut` has no releases as far as `futhark-pkg` (and hence `futhark-docbot`) is concerned.  The tags must be of the form `vX.Y.Z`.

**Comment by Munksgaard** [comment]
Ah, I see! @vmchale, I'm guessing you'd like to see this :-)

**Comment by vmchale** [comment]
Oh yes, I suppose I will have to verify correctness first but that would be quite nice :)
